#Desafio03 Kubdev

name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  CD:
   runs-on: ubuntu-latest
   needs: [CI]
   steps:
    - uses: actions/checkout@v2
    - uses: azure/k8s-actions/k8s-set-context@master
      with:
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Deploy Mongo
      uses: Azure/k8s-deploy@v1
      with:        
        manifests: |
          deploy.yaml
    - name: Deploy Web
      uses: Azure/k8s-deploy@v1
      with:        
        manifests: |
          webdeploy.yaml
        images: httpd:${{ github.run_number }}
